name: embla
description: A friendly web server transport layer for server side Dart apps
version: 0.1.5
author: Emil Persson <emil.n.persson@gmail.com>
homepage: https://github.com/emilniklas/embla

executables:
  embla:

environment:
  sdk: ">=1.12.0 <2.0.0"

dependencies:
  container: ^0.1.2
  stack_trace: ^1.6.0
  shelf: ^0.6.4
  shelf_static: ^0.2.3

dev_dependencies:
  test: any
  quark: any
